application: ucsmsvote
version: 1
runtime: python
api_version: 1

handlers:
- url: /vote
  script: main.py

- url: /poll.*
  script: main.py

- url: /option.*
  script: main.py

- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /
  static_dir: public